# Generated by Django 5.2.9 on 2025-12-25 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کارت')),
                ('image', models.ImageField(upload_to='cards/', verbose_name='تصویر کارت')),
                ('rarity', models.CharField(choices=[('COMMON', 'معمولی'), ('RARE', 'نادر'), ('EPIC', 'حماسی'), ('LEGENDARY', 'افسانه\u200cای')], default='COMMON', max_length=20)),
                ('mining_rate', models.PositiveIntegerField(default=1, verbose_name='نرخ استخراج (سکه در ساعت)')),
                ('max_supply', models.PositiveIntegerField(verbose_name='تعداد کل موجود (Limited Supply)')),
                ('minted_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تولید شده تا الان')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.BigIntegerField(default=0, verbose_name='سکه (Coins)')),
                ('gems', models.BigIntegerField(default=0, verbose_name='الماس (Gems)')),
                ('last_claim_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('is_listed_in_market', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.playerprofile')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='game.cardtemplate')),
            ],
            options={
                'unique_together': {('template', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_gems', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='قیمت (الماس)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='game.playerprofile')),
                ('card_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.usercard')),
            ],
        ),
    ]
