# Generated by Django 5.2.9 on 2025-12-25 14:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام آواتار')),
                ('image', models.ImageField(upload_to='avatars/', verbose_name='تصویر')),
                ('is_premium', models.BooleanField(default=False, verbose_name='پولی است؟')),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='packs/')),
                ('price', models.PositiveIntegerField()),
                ('currency_type', models.CharField(choices=[('GEMS', 'الماس'), ('VOW', 'Vow Fragments'), ('COINS', 'سکه')], default='GEMS', max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='price_gems',
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='price_vow',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='قیمت (Vow)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='slot_1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_slot_1', to='game.usercard'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='slot_2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_slot_2', to='game.usercard'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='slot_3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_slot_3', to='game.usercard'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='vow_fragments',
            field=models.BigIntegerField(default=0, verbose_name='Vow Fragments'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='image',
            field=models.ImageField(upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='max_supply',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='mining_rate',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='minted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cardtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='coins',
            field=models.BigIntegerField(default=0, verbose_name='سکه (Gold)'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.avatar'),
        ),
    ]
