# Generated by Django 5.2.9 on 2025-12-25 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_avatar_pack_remove_marketlisting_price_gems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketlisting',
            name='price_vow',
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='price_gems',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='قیمت (Gems)'),
            preserve_default=False,
        ),
    ]
