# Generated by Django 5.0.1 on 2025-12-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_marketlisting_price_vow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='current_mining_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='نرخ استخراج فعلی'),
        ),
    ]
