# Generated by Django 5.0.1 on 2025-12-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playerprofile_current_mining_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='سطح'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='xp',
            field=models.BigIntegerField(default=0, verbose_name='تجربه'),
        ),
    ]
