# Generated by Django 5.0.1 on 2025-12-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_playerprofile_level_playerprofile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='card_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد کارت در پک'),
        ),
        migrations.AddField(
            model_name='pack',
            name='chance_common',
            field=models.PositiveIntegerField(default=60, verbose_name='شانس معمولی (%)'),
        ),
        migrations.AddField(
            model_name='pack',
            name='chance_epic',
            field=models.PositiveIntegerField(default=9, verbose_name='شانس حماسی (%)'),
        ),
        migrations.AddField(
            model_name='pack',
            name='chance_legendary',
            field=models.PositiveIntegerField(default=1, verbose_name='شانس افسانه\u200cای (%)'),
        ),
        migrations.AddField(
            model_name='pack',
            name='chance_rare',
            field=models.PositiveIntegerField(default=30, verbose_name='شانس نادر (%)'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='currency_type',
            field=models.CharField(choices=[('GEMS', 'الماس'), ('VOW', 'Vow Fragments'), ('COINS', 'سکه')], default='GEMS', max_length=10, verbose_name='نوع ارز'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='image',
            field=models.ImageField(upload_to='packs/', verbose_name='تصویر پک'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام پک'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
    ]
