# Generated by Django 5.0.1 on 2025-12-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_pack_card_count_pack_chance_common_pack_chance_epic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات پک برای نمایش به کاربر', null=True),
        ),
    ]
