# Generated by Django 5.0.1 on 2025-12-26 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_pack_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketlisting',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='card_instance',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='price_gems',
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='card',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='market_listing', to='game.usercard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='currency',
            field=models.CharField(choices=[('COINS', 'Scoin'), ('GEMS', 'Gem'), ('FRAGMENTS', 'Vow Fragment')], default='COINS', max_length=10),
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercard',
            name='is_listed',
            field=models.BooleanField(default=False, help_text='آیا کارت در مارکت برای فروش است؟'),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
