# Generated by Django 5.2.9 on 2025-12-27 00:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_marketlisting_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketlisting',
            old_name='card',
            new_name='card_instance',
        ),
        migrations.AddField(
            model_name='marketlisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='currency',
            field=models.CharField(choices=[('COINS', 'سکه'), ('GEMS', 'الماس'), ('FRAGMENTS', 'Vow Fragment')], default='GEMS', max_length=10, verbose_name='نوع ارز'),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='game.playerprofile'),
        ),
    ]
