# Generated by Django 5.2.9 on 2025-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_card_marketlisting_card_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercard',
            name='is_listed',
        ),
        migrations.AlterField(
            model_name='usercard',
            name='is_listed_in_market',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='usercard',
            index=models.Index(fields=['owner', 'is_listed_in_market'], name='game_userca_owner_i_21d4cf_idx'),
        ),
    ]
