# Generated by Django 5.2.9 on 2025-12-27 15:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_usercard_is_listed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketlisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'لیست بازار', 'verbose_name_plural': 'لیست\u200cهای بازار'},
        ),
        migrations.RemoveField(
            model_name='marketlisting',
            name='currency',
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='قیمت (Vow Fragments)'),
        ),
        migrations.AlterField(
            model_name='marketlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to='game.playerprofile'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['is_active', '-created_at'], name='game_market_is_acti_4e9d26_idx'),
        ),
    ]
