"""
Django settings for oathbreakers project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# ENVIRONMENT DETECTION
# ============================================================
# Set ENVIRONMENT=production in production to enable strict mode
ENVIRONMENT = os.environ.get('ENVIRONMENT', 'development')  # development, staging, production
IS_PRODUCTION = ENVIRONMENT == 'production'


# ============================================================
# SECRET KEY
# ============================================================
# SECURITY WARNING: keep the secret key used in production secret!
if IS_PRODUCTION:
    # Production: SECRET_KEY is REQUIRED
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
    if not SECRET_KEY:
        raise ValueError(
            "ERROR: DJANGO_SECRET_KEY environment variable must be set in production!\n"
            "Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
        )
else:
    # Development: Use a default insecure key (can be overridden via env var)
    SECRET_KEY = os.environ.get(
        'DJANGO_SECRET_KEY',
        'django-insecure-dev-only-zxcv1234asdfqwerty9876poiuytrewqasdfghjkl'
    )


# ============================================================
# DEBUG
# ============================================================
# SECURITY WARNING: don't run with debug turned on in production!
if IS_PRODUCTION:
    DEBUG = False  # Always False in production
else:
    DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'


# ============================================================
# ALLOWED HOSTS
# ============================================================
# In production set this to your domain(s) via environment or settings override
ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'game',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oathbreakers.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.media',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oathbreakers.wsgi.application'


# ============================================================
# DATABASE
# ============================================================
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database password validation
if IS_PRODUCTION:
    # Production: POSTGRES_PASSWORD is REQUIRED
    db_password = os.environ.get('POSTGRES_PASSWORD')
    if not db_password:
        raise ValueError("ERROR: POSTGRES_PASSWORD environment variable must be set in production!")
else:
    # Development: Use default password (can be overridden via env var)
    db_password = os.environ.get('POSTGRES_PASSWORD', 'mehran9731')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'oathbearkers_db'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': db_password,
        'HOST': os.environ.get('POSTGRES_HOST', '127.0.0.1'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATIC_URL = '/static/'

# مسیر فیزیکی فایل‌های استاتیک هنگام collectstatic (برای سرور واقعی)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# مسیرهای اضافی برای جستجوی فایل‌های استاتیک در حالت توسعه
# اگر فولدر static در روت پروژه وجود داشته باشد، آن را اضافه می‌کنیم تا هشدار W004 نگیریم.
STATICFILES_DIRS = []
_root_static_dir = BASE_DIR / 'static'
if _root_static_dir.exists():
    STATICFILES_DIRS.append(_root_static_dir)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
